site_name: Image Captioning for antique greece archeological images
docs_dir: docs
use_directory_urls: false
theme:
  name: 'material'
  palette:
    scheme: slate  # Modo oscuro por defecto
    primary: 'indigo'
    accent: 'indigo'
    toggle:
      icon: material/light-dark
      name: Switch between Light and Dark mode
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  features:
    - navigation.tabs
    - navigation.sections
    - search.share
    - search.highlight
nav:
  - Home: index.md
  - Sources:
      - Process Features: sources/processFeatures.md
      - Process Train Models: sources/processTrain.md
      - Data Management: sources/dataManager.md
  - Common:
      - common: sources/common/common.md
      - paramsManager: sources/common/paramsManager.md
      - utils: sources/common/utils.md
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.tasklist
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx  # Especificar el estilo Sphinx
          import:
            - ~/Documentos/proyectos/HumanidadesDigitales/ImageCaption